# Generated by Django 4.2.20 on 2025-06-11 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projek', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relasi', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relasis', to='kel5_app.projek')),
            ],
        ),
        migrations.CreateModel(
            name='Perencanaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment', models.CharField(max_length=255)),
                ('pemeliharaan', models.CharField(max_length=255)),
                ('operasi', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perencanaans', to='kel5_app.projek')),
            ],
        ),
        migrations.CreateModel(
            name='Meaningful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectives', models.TextField()),
                ('outcomes', models.TextField()),
                ('indicator', models.TextField()),
                ('properties', models.TextField()),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_akhir', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meaningfuls', to='kel5_app.projek')),
            ],
        ),
        migrations.CreateModel(
            name='Implementasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proses', models.TextField()),
                ('teknologi', models.TextField()),
                ('bangun', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implementasis', to='kel5_app.projek')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automate', models.TextField()),
                ('prompt', models.TextField()),
                ('annotate', models.TextField()),
                ('organization', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='kel5_app.projek')),
            ],
        ),
        migrations.CreateModel(
            name='Batasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batasan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batasans', to='kel5_app.projek')),
            ],
        ),
    ]
