# Generated by Django 4.2.20 on 2025-06-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kel5_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meaningful',
            name='tanggal_akhir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meaningful',
            name='tanggal_mulai',
            field=models.DateField(blank=True, null=True),
        ),
    ]
