# Generated by Django 4.2.21 on 2025-06-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kel5_app', '0002_alter_meaningful_tanggal_akhir_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('mulai', models.DateField()),
                ('selesai', models.DateField()),
                ('penanggungjawab', models.CharField(max_length=255)),
                ('jumlah', models.IntegerField()),
                ('pendanaan', models.CharField(max_length=255)),
                ('aktivitas1', models.CharField(blank=True, max_length=255, null=True)),
                ('aktivitas2', models.CharField(blank=True, max_length=255, null=True)),
                ('aktivitas3', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
