# Generated by Django 4.2.21 on 2025-07-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kel5_app', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaProjek', models.TextField()),
                ('meaningful', models.FileField(upload_to='dokumen/')),
                ('experience', models.FileField(upload_to='dokumen/')),
                ('implementasi', models.FileField(upload_to='dokumen/')),
                ('batasan', models.FileField(upload_to='dokumen/')),
                ('perencanaan', models.FileField(upload_to='dokumen/')),
            ],
        ),
    ]
