# Generated by Django 4.2.21 on 2025-07-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kel5_app', '0005_toexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaKelompok', models.TextField()),
                ('deskripsi', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
    ]
