# Generated by Django 4.2.21 on 2025-07-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kel5_app', '0006_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='status',
            field=models.IntegerField(),
        ),
    ]
