# Generated by Django 4.2.21 on 2025-07-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kel5_app', '0007_alter_management_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='status',
            field=models.TextField(),
        ),
    ]
